spring:
  application:
    name: 'jwtauth'

  flyway:
    enable: true
    location: 'db/migrations/tenants/postgres'

  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/jwtauth_db'
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect